spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  #开发环境
  profiles: dev
  application: 
    name: microservicespringcloud-config-dream-dev
---
spring: 
  #测试环境
  profiles: test
  application: 
    name: microservicespringcloud-config-dream-test

#一定要保存为UTF-8格式