spring: 
  profiles: 
    active:
    - dev
---
server: 
  #注册中心占用7001端口，冒号后面必须要有空格
  port: 7001
  
spring: 
  profiles: dev
  application: 
    name: microservicespringcloud-config-eureka-client

eureka: 
  instance: 
    hostname: eureka7001
  client: 
    # 当前的eureka-server自己不注册进服务列表中
    register-with-eureka: false
    # 不通过eureka获得注册信息
    fetch-registry: false
    service-url: 
      defaultZone: http://eureka7001:7001/eureka/
---
server: 
  #注册中心占用7001端口，冒号后面必须要有空格
  port: 7001

spring: 
  profiles: test
  application: 
    name: microservicespringcloud-config-eureka-client
    
eureka: 
  instance: 
    hostname: eureka7001
  client: 
    # 当前的eureka-server自己不注册进服务列表中
    register-with-eureka: false
    # 不通过eureka获得注册信息
    fetch-registry: false
    service-url: 
      defaultZone: http://eureka7001:7001/eureka/